# src/main/resources/secrets.properties
# leaving secrets empty for local dev; using root with no password for local MySQL
local.datasource.url=jdbc:mysql://localhost:3306/pos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
local.datasource.username=root
local.datasource.password=